server:
  port: 80

eureka:
  instance:
    instance-id: tangel-springcloud-consumer80
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
    hostname: tangel-springcloud-consumer80
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka

# 微服务名称
spring:
  application:
    name: tangel-springcloud-consumer80