server:
  port: 8009

eureka:
  instance:
    instance-id: tangel-springcloud-hystrix8009
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
    hostname: tangel-springcloud-hystrix8009
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka

# 微服务名称
spring:
  application:
    name: tangel-springcloud-hystrix