server:
  port: 8001

eureka:
  instance:
    instance-id: tangel-springcloud-provider8001
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    hostname: tangel-springcloud-provider8001
    # 标记，表示在猜测主机名时，服务器的IP地址应与操作系统报告的主机名相对应。
    prefer-ip-address: true             # Flag to say that, when guessing a hostname, the IP address of the server should be used in prference to the hostname reported by the OS.
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

spring:
  application:
    name: tangel-springcloud-provider8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud?userUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tangel.springcloud.entities

swagger:
  base-package: com.tangel.springcloud.controller