server:
  port: 8001

spring:
  application:
    name: tangel-springcloud-payment-servuce
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud?userUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tangel.springcloud.entities

eureka:
  instance:
    instance-id: tangel-springcloud-provider8001
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    hostname: tangel-springcloud-provider8001
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: true
    fetch-registry: true