server:
  port: 8007

spring:
  application:
    name: tangel-springcloud-consul-comsumer

  #consul配置
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  # 数据库相关
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud?userUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
